FROM node:21.6.0-slim

RUN apt-get update -y && apt-get install git -y

RUN git clone --branch infimum https://github.com/rhysbalevicius/substrate-front-end-template

WORKDIR /substrate-front-end-template

RUN npm install
EXPOSE 8000