FROM rust:1.74.1-slim
LABEL Rhys Balevicius "rhys@apollos.tech"

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV RUST_BACKTRACE 1
ENV CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG true

RUN rustup update \
    && rustup update nightly \
    && rustup install nightly-2023-08-31 \
    && rustup override set nightly-2023-08-31 \
    && rustup target add wasm32-unknown-unknown --toolchain nightly-2023-08-31

RUN apt-get update -y && apt-get install -y \
    build-essential \
    clang \
    curl \
    git \
    libssl-dev \
    protobuf-compiler 

RUN git clone https://github.com/rhysbalevicius/substrate-node-template.git /node

COPY ./.dev/Cargo.toml ./node/Cargo.toml
COPY ./.dev/runtime/Cargo.toml ./node/runtime/Cargo.toml
COPY ./.dev/runtime/src/lib.rs ./node/runtime/src/lib.rs
COPY ./pallet ./node/pallets/infimum

WORKDIR /node
RUN cargo build --release
