name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          rustup default nightly
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown

      - name: Check Build
        run: |
          SKIP_WASM_BUILD=1 cargo +nightly check --release --manifest-path=./pallet/Cargo.toml

      - name: Run tests
        run: |
          cargo test --all-features --manifest-path=./pallet/Cargo.toml
